# WHIP/WHEP基础地址，不要在末尾添加查询参数
push_server_url=http://82.156.137.234/rtc/v1/whip/
pull_server_url=http://82.156.137.234/rtc/v1/whep/

# 最终流名称由TransportEngine生成为：
# rtc_test_room_publisher
room_id=rtc_test_room
local_user_id=publisher

# 回环测试订阅自己发布的流
subscribe_user_id=publisher

# Oryx配置
whip_secret=18d44630c086480783f62f33dbb7e09a
rtc_external_address=82.156.137.234:8000

video_file=/home/ewas/VC_code/meeting-client/source/camera_640x480_i420.yuv
audio_file=/home/ewas/VC_code/meeting-client/source/microphone_48000hz_2ch_f32le.pcm

duration_seconds=30