mode=join

local_user_id=joiner
remote_user_id=creator
room_id=vce_media_test

push_server_url=http://82.156.137.234/rtc/v1/whip/
pull_server_url=http://82.156.137.234/rtc/v1/whep/
app_name=live
rtc_external_address=82.156.137.234:8000
whip_secret=18d44630c086480783f62f33dbb7e09a

camera_device_id=/dev/video1
microphone_device_id=alsa_input.usb-Generic_USB2.0_Device_20170726905926-00.mono-fallback
speaker_device_id=AB USB Audio 模拟立体声

sample_rate=48000
channels=2
camera_video_format=YUYV
video_width=640
video_height=480
video_fps=30

enable_video=true
enable_audio=true
expect_remote_video=true
expect_remote_audio=true

duration_seconds=300
subscribe_retry_seconds=5

save_received_media=false
received_video_file=joiner_received_creator_640x480_i420.yuv
received_audio_file=joiner_received_creator_48000hz_2ch_f32le.pcm