// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: meeting_service.proto
#ifndef GRPC_meeting_5fservice_2eproto__INCLUDED
#define GRPC_meeting_5fservice_2eproto__INCLUDED

#include "meeting_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace meeting_service {

// 定义会议服务
class MeetingService final {
 public:
  static constexpr char const* service_full_name() {
    return "meeting_service.MeetingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 创建会议
    virtual ::grpc::Status CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::meeting_service::CreateMeetingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>> AsyncCreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>>(AsyncCreateMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>> PrepareAsyncCreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>>(PrepareAsyncCreateMeetingRaw(context, request, cq));
    }
    // 加入会议
    virtual ::grpc::Status JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::meeting_service::JoinMeetingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>> AsyncJoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>>(AsyncJoinMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>> PrepareAsyncJoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>>(PrepareAsyncJoinMeetingRaw(context, request, cq));
    }
    // 离开会议
    virtual ::grpc::Status LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::meeting_service::LeaveMeetingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>> AsyncLeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>>(AsyncLeaveMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>> PrepareAsyncLeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>>(PrepareAsyncLeaveMeetingRaw(context, request, cq));
    }
    // 结束会议
    virtual ::grpc::Status EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::meeting_service::EndMeetingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>> AsyncEndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>>(AsyncEndMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>> PrepareAsyncEndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>>(PrepareAsyncEndMeetingRaw(context, request, cq));
    }
    // 获取会议列表
    virtual ::grpc::Status GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::meeting_service::GetMeetingListResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>> AsyncGetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>>(AsyncGetMeetingListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>> PrepareAsyncGetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>>(PrepareAsyncGetMeetingListRaw(context, request, cq));
    }
    // 订阅会议事件（服务端流式推送）
    std::unique_ptr< ::grpc::ClientReaderInterface< ::meeting_service::MeetingEvent>> SubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::meeting_service::MeetingEvent>>(SubscribeMeetingEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>> AsyncSubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>>(AsyncSubscribeMeetingEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>> PrepareAsyncSubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>>(PrepareAsyncSubscribeMeetingEventsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 创建会议
      virtual void CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 加入会议
      virtual void JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 离开会议
      virtual void LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 结束会议
      virtual void EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取会议列表
      virtual void GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 订阅会议事件（服务端流式推送）
      virtual void SubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ClientReadReactor< ::meeting_service::MeetingEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>* AsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::CreateMeetingResponse>* PrepareAsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>* AsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::JoinMeetingResponse>* PrepareAsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>* AsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::LeaveMeetingResponse>* PrepareAsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>* AsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::EndMeetingResponse>* PrepareAsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>* AsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::meeting_service::GetMeetingListResponse>* PrepareAsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::meeting_service::MeetingEvent>* SubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>* AsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::meeting_service::MeetingEvent>* PrepareAsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::meeting_service::CreateMeetingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>> AsyncCreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>>(AsyncCreateMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>> PrepareAsyncCreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>>(PrepareAsyncCreateMeetingRaw(context, request, cq));
    }
    ::grpc::Status JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::meeting_service::JoinMeetingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>> AsyncJoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>>(AsyncJoinMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>> PrepareAsyncJoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>>(PrepareAsyncJoinMeetingRaw(context, request, cq));
    }
    ::grpc::Status LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::meeting_service::LeaveMeetingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>> AsyncLeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>>(AsyncLeaveMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>> PrepareAsyncLeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>>(PrepareAsyncLeaveMeetingRaw(context, request, cq));
    }
    ::grpc::Status EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::meeting_service::EndMeetingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>> AsyncEndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>>(AsyncEndMeetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>> PrepareAsyncEndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>>(PrepareAsyncEndMeetingRaw(context, request, cq));
    }
    ::grpc::Status GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::meeting_service::GetMeetingListResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>> AsyncGetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>>(AsyncGetMeetingListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>> PrepareAsyncGetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>>(PrepareAsyncGetMeetingListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::meeting_service::MeetingEvent>> SubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::meeting_service::MeetingEvent>>(SubscribeMeetingEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>> AsyncSubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>>(AsyncSubscribeMeetingEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>> PrepareAsyncSubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>>(PrepareAsyncSubscribeMeetingEventsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, std::function<void(::grpc::Status)>) override;
      void JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, std::function<void(::grpc::Status)>) override;
      void LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, std::function<void(::grpc::Status)>) override;
      void EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, std::function<void(::grpc::Status)>) override;
      void GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ClientReadReactor< ::meeting_service::MeetingEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>* AsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>* PrepareAsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>* AsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>* PrepareAsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>* AsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>* PrepareAsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>* AsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>* PrepareAsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>* AsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>* PrepareAsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::meeting_service::MeetingEvent>* SubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request) override;
    ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>* AsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>* PrepareAsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateMeeting_;
    const ::grpc::internal::RpcMethod rpcmethod_JoinMeeting_;
    const ::grpc::internal::RpcMethod rpcmethod_LeaveMeeting_;
    const ::grpc::internal::RpcMethod rpcmethod_EndMeeting_;
    const ::grpc::internal::RpcMethod rpcmethod_GetMeetingList_;
    const ::grpc::internal::RpcMethod rpcmethod_SubscribeMeetingEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 创建会议
    virtual ::grpc::Status CreateMeeting(::grpc::ServerContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response);
    // 加入会议
    virtual ::grpc::Status JoinMeeting(::grpc::ServerContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response);
    // 离开会议
    virtual ::grpc::Status LeaveMeeting(::grpc::ServerContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response);
    // 结束会议
    virtual ::grpc::Status EndMeeting(::grpc::ServerContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response);
    // 获取会议列表
    virtual ::grpc::Status GetMeetingList(::grpc::ServerContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response);
    // 订阅会议事件（服务端流式推送）
    virtual ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateMeeting(::grpc::ServerContext* context, ::meeting_service::CreateMeetingRequest* request, ::grpc::ServerAsyncResponseWriter< ::meeting_service::CreateMeetingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinMeeting(::grpc::ServerContext* context, ::meeting_service::JoinMeetingRequest* request, ::grpc::ServerAsyncResponseWriter< ::meeting_service::JoinMeetingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLeaveMeeting(::grpc::ServerContext* context, ::meeting_service::LeaveMeetingRequest* request, ::grpc::ServerAsyncResponseWriter< ::meeting_service::LeaveMeetingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EndMeeting() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEndMeeting(::grpc::ServerContext* context, ::meeting_service::EndMeetingRequest* request, ::grpc::ServerAsyncResponseWriter< ::meeting_service::EndMeetingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMeetingList(::grpc::ServerContext* context, ::meeting_service::GetMeetingListRequest* request, ::grpc::ServerAsyncResponseWriter< ::meeting_service::GetMeetingListResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeMeetingEvents(::grpc::ServerContext* context, ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ServerAsyncWriter< ::meeting_service::MeetingEvent>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateMeeting<WithAsyncMethod_JoinMeeting<WithAsyncMethod_LeaveMeeting<WithAsyncMethod_EndMeeting<WithAsyncMethod_GetMeetingList<WithAsyncMethod_SubscribeMeetingEvents<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response) { return this->CreateMeeting(context, request, response); }));}
    void SetMessageAllocatorFor_CreateMeeting(
        ::grpc::MessageAllocator< ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response) { return this->JoinMeeting(context, request, response); }));}
    void SetMessageAllocatorFor_JoinMeeting(
        ::grpc::MessageAllocator< ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response) { return this->LeaveMeeting(context, request, response); }));}
    void SetMessageAllocatorFor_LeaveMeeting(
        ::grpc::MessageAllocator< ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LeaveMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EndMeeting() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response) { return this->EndMeeting(context, request, response); }));}
    void SetMessageAllocatorFor_EndMeeting(
        ::grpc::MessageAllocator< ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EndMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response) { return this->GetMeetingList(context, request, response); }));}
    void SetMessageAllocatorFor_GetMeetingList(
        ::grpc::MessageAllocator< ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMeetingList(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackServerStreamingHandler< ::meeting_service::SubscribeMeetingEventsRequest, ::meeting_service::MeetingEvent>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request) { return this->SubscribeMeetingEvents(context, request); }));
    }
    ~WithCallbackMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::meeting_service::MeetingEvent>* SubscribeMeetingEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateMeeting<WithCallbackMethod_JoinMeeting<WithCallbackMethod_LeaveMeeting<WithCallbackMethod_EndMeeting<WithCallbackMethod_GetMeetingList<WithCallbackMethod_SubscribeMeetingEvents<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EndMeeting() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateMeeting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinMeeting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLeaveMeeting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EndMeeting() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEndMeeting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMeetingList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeMeetingEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateMeeting(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->JoinMeeting(context, request, response); }));
    }
    ~WithRawCallbackMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LeaveMeeting(context, request, response); }));
    }
    ~WithRawCallbackMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LeaveMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EndMeeting() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EndMeeting(context, request, response); }));
    }
    ~WithRawCallbackMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EndMeeting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMeetingList(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMeetingList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SubscribeMeetingEvents(context, request); }));
    }
    ~WithRawCallbackMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SubscribeMeetingEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateMeeting() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse>* streamer) {
                       return this->StreamedCreateMeeting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::CreateMeetingRequest* /*request*/, ::meeting_service::CreateMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateMeeting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::meeting_service::CreateMeetingRequest,::meeting_service::CreateMeetingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_JoinMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_JoinMeeting() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse>* streamer) {
                       return this->StreamedJoinMeeting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_JoinMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status JoinMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::JoinMeetingRequest* /*request*/, ::meeting_service::JoinMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJoinMeeting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::meeting_service::JoinMeetingRequest,::meeting_service::JoinMeetingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LeaveMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LeaveMeeting() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse>* streamer) {
                       return this->StreamedLeaveMeeting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LeaveMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LeaveMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::LeaveMeetingRequest* /*request*/, ::meeting_service::LeaveMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLeaveMeeting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::meeting_service::LeaveMeetingRequest,::meeting_service::LeaveMeetingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EndMeeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EndMeeting() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse>* streamer) {
                       return this->StreamedEndMeeting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EndMeeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EndMeeting(::grpc::ServerContext* /*context*/, const ::meeting_service::EndMeetingRequest* /*request*/, ::meeting_service::EndMeetingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEndMeeting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::meeting_service::EndMeetingRequest,::meeting_service::EndMeetingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMeetingList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMeetingList() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse>* streamer) {
                       return this->StreamedGetMeetingList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMeetingList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMeetingList(::grpc::ServerContext* /*context*/, const ::meeting_service::GetMeetingListRequest* /*request*/, ::meeting_service::GetMeetingListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMeetingList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::meeting_service::GetMeetingListRequest,::meeting_service::GetMeetingListResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateMeeting<WithStreamedUnaryMethod_JoinMeeting<WithStreamedUnaryMethod_LeaveMeeting<WithStreamedUnaryMethod_EndMeeting<WithStreamedUnaryMethod_GetMeetingList<Service > > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SubscribeMeetingEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SubscribeMeetingEvents() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::meeting_service::SubscribeMeetingEventsRequest, ::meeting_service::MeetingEvent>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::meeting_service::SubscribeMeetingEventsRequest, ::meeting_service::MeetingEvent>* streamer) {
                       return this->StreamedSubscribeMeetingEvents(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SubscribeMeetingEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubscribeMeetingEvents(::grpc::ServerContext* /*context*/, const ::meeting_service::SubscribeMeetingEventsRequest* /*request*/, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSubscribeMeetingEvents(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::meeting_service::SubscribeMeetingEventsRequest,::meeting_service::MeetingEvent>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SubscribeMeetingEvents<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateMeeting<WithStreamedUnaryMethod_JoinMeeting<WithStreamedUnaryMethod_LeaveMeeting<WithStreamedUnaryMethod_EndMeeting<WithStreamedUnaryMethod_GetMeetingList<WithSplitStreamingMethod_SubscribeMeetingEvents<Service > > > > > > StreamedService;
};

}  // namespace meeting_service


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_meeting_5fservice_2eproto__INCLUDED
