// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: meeting_service.proto

#include "meeting_service.pb.h"
#include "meeting_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace meeting_service {

static const char* MeetingService_method_names[] = {
  "/meeting_service.MeetingService/CreateMeeting",
  "/meeting_service.MeetingService/JoinMeeting",
  "/meeting_service.MeetingService/LeaveMeeting",
  "/meeting_service.MeetingService/EndMeeting",
  "/meeting_service.MeetingService/GetMeetingList",
  "/meeting_service.MeetingService/SubscribeMeetingEvents",
};

std::unique_ptr< MeetingService::Stub> MeetingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MeetingService::Stub> stub(new MeetingService::Stub(channel, options));
  return stub;
}

MeetingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateMeeting_(MeetingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_JoinMeeting_(MeetingService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LeaveMeeting_(MeetingService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EndMeeting_(MeetingService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMeetingList_(MeetingService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubscribeMeetingEvents_(MeetingService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MeetingService::Stub::CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::meeting_service::CreateMeetingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateMeeting_, context, request, response);
}

void MeetingService::Stub::async::CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateMeeting_, context, request, response, std::move(f));
}

void MeetingService::Stub::async::CreateMeeting(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateMeeting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>* MeetingService::Stub::PrepareAsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::meeting_service::CreateMeetingResponse, ::meeting_service::CreateMeetingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateMeeting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::CreateMeetingResponse>* MeetingService::Stub::AsyncCreateMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::CreateMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateMeetingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MeetingService::Stub::JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::meeting_service::JoinMeetingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_JoinMeeting_, context, request, response);
}

void MeetingService::Stub::async::JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_JoinMeeting_, context, request, response, std::move(f));
}

void MeetingService::Stub::async::JoinMeeting(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_JoinMeeting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>* MeetingService::Stub::PrepareAsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::meeting_service::JoinMeetingResponse, ::meeting_service::JoinMeetingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_JoinMeeting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::JoinMeetingResponse>* MeetingService::Stub::AsyncJoinMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::JoinMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncJoinMeetingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MeetingService::Stub::LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::meeting_service::LeaveMeetingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LeaveMeeting_, context, request, response);
}

void MeetingService::Stub::async::LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveMeeting_, context, request, response, std::move(f));
}

void MeetingService::Stub::async::LeaveMeeting(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveMeeting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>* MeetingService::Stub::PrepareAsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::meeting_service::LeaveMeetingResponse, ::meeting_service::LeaveMeetingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LeaveMeeting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::LeaveMeetingResponse>* MeetingService::Stub::AsyncLeaveMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::LeaveMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLeaveMeetingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MeetingService::Stub::EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::meeting_service::EndMeetingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EndMeeting_, context, request, response);
}

void MeetingService::Stub::async::EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EndMeeting_, context, request, response, std::move(f));
}

void MeetingService::Stub::async::EndMeeting(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EndMeeting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>* MeetingService::Stub::PrepareAsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::meeting_service::EndMeetingResponse, ::meeting_service::EndMeetingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EndMeeting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::EndMeetingResponse>* MeetingService::Stub::AsyncEndMeetingRaw(::grpc::ClientContext* context, const ::meeting_service::EndMeetingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEndMeetingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MeetingService::Stub::GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::meeting_service::GetMeetingListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMeetingList_, context, request, response);
}

void MeetingService::Stub::async::GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeetingList_, context, request, response, std::move(f));
}

void MeetingService::Stub::async::GetMeetingList(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMeetingList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>* MeetingService::Stub::PrepareAsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::meeting_service::GetMeetingListResponse, ::meeting_service::GetMeetingListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMeetingList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::meeting_service::GetMeetingListResponse>* MeetingService::Stub::AsyncGetMeetingListRaw(::grpc::ClientContext* context, const ::meeting_service::GetMeetingListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMeetingListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::meeting_service::MeetingEvent>* MeetingService::Stub::SubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::meeting_service::MeetingEvent>::Create(channel_.get(), rpcmethod_SubscribeMeetingEvents_, context, request);
}

void MeetingService::Stub::async::SubscribeMeetingEvents(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ClientReadReactor< ::meeting_service::MeetingEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::meeting_service::MeetingEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeMeetingEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>* MeetingService::Stub::AsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::meeting_service::MeetingEvent>::Create(channel_.get(), cq, rpcmethod_SubscribeMeetingEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::meeting_service::MeetingEvent>* MeetingService::Stub::PrepareAsyncSubscribeMeetingEventsRaw(::grpc::ClientContext* context, const ::meeting_service::SubscribeMeetingEventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::meeting_service::MeetingEvent>::Create(channel_.get(), cq, rpcmethod_SubscribeMeetingEvents_, context, request, false, nullptr);
}

MeetingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingService::Service, ::meeting_service::CreateMeetingRequest, ::meeting_service::CreateMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::CreateMeetingRequest* req,
             ::meeting_service::CreateMeetingResponse* resp) {
               return service->CreateMeeting(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingService::Service, ::meeting_service::JoinMeetingRequest, ::meeting_service::JoinMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::JoinMeetingRequest* req,
             ::meeting_service::JoinMeetingResponse* resp) {
               return service->JoinMeeting(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingService::Service, ::meeting_service::LeaveMeetingRequest, ::meeting_service::LeaveMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::LeaveMeetingRequest* req,
             ::meeting_service::LeaveMeetingResponse* resp) {
               return service->LeaveMeeting(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingService::Service, ::meeting_service::EndMeetingRequest, ::meeting_service::EndMeetingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::EndMeetingRequest* req,
             ::meeting_service::EndMeetingResponse* resp) {
               return service->EndMeeting(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MeetingService::Service, ::meeting_service::GetMeetingListRequest, ::meeting_service::GetMeetingListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::GetMeetingListRequest* req,
             ::meeting_service::GetMeetingListResponse* resp) {
               return service->GetMeetingList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MeetingService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MeetingService::Service, ::meeting_service::SubscribeMeetingEventsRequest, ::meeting_service::MeetingEvent>(
          [](MeetingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::meeting_service::SubscribeMeetingEventsRequest* req,
             ::grpc::ServerWriter<::meeting_service::MeetingEvent>* writer) {
               return service->SubscribeMeetingEvents(ctx, req, writer);
             }, this)));
}

MeetingService::Service::~Service() {
}

::grpc::Status MeetingService::Service::CreateMeeting(::grpc::ServerContext* context, const ::meeting_service::CreateMeetingRequest* request, ::meeting_service::CreateMeetingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MeetingService::Service::JoinMeeting(::grpc::ServerContext* context, const ::meeting_service::JoinMeetingRequest* request, ::meeting_service::JoinMeetingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MeetingService::Service::LeaveMeeting(::grpc::ServerContext* context, const ::meeting_service::LeaveMeetingRequest* request, ::meeting_service::LeaveMeetingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MeetingService::Service::EndMeeting(::grpc::ServerContext* context, const ::meeting_service::EndMeetingRequest* request, ::meeting_service::EndMeetingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MeetingService::Service::GetMeetingList(::grpc::ServerContext* context, const ::meeting_service::GetMeetingListRequest* request, ::meeting_service::GetMeetingListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MeetingService::Service::SubscribeMeetingEvents(::grpc::ServerContext* context, const ::meeting_service::SubscribeMeetingEventsRequest* request, ::grpc::ServerWriter< ::meeting_service::MeetingEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace meeting_service
#include <grpcpp/ports_undef.inc>

